-- begin CEUDV_ORDER
alter table CEUDV_ORDER add constraint FK_CEUDV_ORDER_ON_CUSTOMER foreign key (CUSTOMER_ID) references CEUDV_CUSTOMER(ID)^
create index IDX_CEUDV_ORDER_ON_CUSTOMER on CEUDV_ORDER (CUSTOMER_ID)^
-- end CEUDV_ORDER
-- begin CEUDV_CUSTOMER
alter table CEUDV_CUSTOMER add constraint FK_CEUDV_CUSTOMER_ON_COUNTRY foreign key (COUNTRY_ID) references CEUDV_COUNTRY(ID)^
alter table CEUDV_CUSTOMER add constraint FK_CEUDV_CUSTOMER_ON_ACCOUNT_MANAGER foreign key (ACCOUNT_MANAGER_ID) references SEC_USER(ID)^
create index IDX_CEUDV_CUSTOMER_ON_COUNTRY on CEUDV_CUSTOMER (COUNTRY_ID)^
create index IDX_CEUDV_CUSTOMER_ON_ACCOUNT_MANAGER on CEUDV_CUSTOMER (ACCOUNT_MANAGER_ID)^
-- end CEUDV_CUSTOMER
-- begin CEUDV_ACCOUNT_MANAGER_DEFAULT_ORDER_PRIORITY
alter table CEUDV_ACCOUNT_MANAGER_DEFAULT_ORDER_PRIORITY add constraint FK_CEUDV_ACCOUNT_MANAGER_DEFAULT_ORDER_PRIORITY_ON_ACCOUNT_MANAGER foreign key (ACCOUNT_MANAGER_ID) references SEC_USER(ID)^
create index IDX_CEUDV_ACCOUNT_MANAGER_DEFAULT_ORDER_PRIORITY_ON_ACCOUNT_MANAGER on CEUDV_ACCOUNT_MANAGER_DEFAULT_ORDER_PRIORITY (ACCOUNT_MANAGER_ID)^
-- end CEUDV_ACCOUNT_MANAGER_DEFAULT_ORDER_PRIORITY
