alter table CEUDV_CUSTOMER add constraint FK_CEUDV_CUSTOMER_ON_ACCOUNT_MANAGER foreign key (ACCOUNT_MANAGER_ID) references SEC_USER(ID);
create index IDX_CEUDV_CUSTOMER_ON_ACCOUNT_MANAGER on CEUDV_CUSTOMER (ACCOUNT_MANAGER_ID);
